# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c24ccc9856e3be49b49b0b499eed508536e4e089c81b7ec14c51a60f24ad14134ca6aa869ed73aea6926f2969015e85d9571c3674a024186e72cf824e4013274

test:
  secret_key_base: ddd4414b4eb36f6abf362063c2f435884c1baaf7e1da5e0c23d53277813c3ccc319f6c877111d0bd2456ffe38fbd298c1f3d7171923c45b9f60f90ddbc950daa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
